### ISSUE TITLE
Wine integration request

### ISSUE THREAD

**Issue by lucasmr** [Zutatensuppe/DiabloInterface#12]
Would love to have the interface running via wine, that way I don't need to boot into windows to play. The interface is looking for game.exe atm.

**Comment by Zutatensuppe** [comment]
Sorry to say that, but most likely this wont be happening. I installed ubuntu in a vm and tried to get D2 running, without success (directx or graphic issues i suppose).
DiabloInterface launched, but only the main window, also with terrible layout (was cut in half).
I dont even know if you can debug c# applications in linux correctly. 

So unless someone with a real linux system (and some knowledge about debugging c# apps in it) will take a look at this, there are very low chances that this will be a thing. :disappointed:

**Comment by qhris** [comment]
Going with what @Zutatensuppe previously commented, we're not going to support this for now.
