### ISSUE TITLE
Add percentage counter for 100% runs

### ISSUE THREAD

**Issue by Teo1904** [Zutatensuppe/DiabloInterface#14]
For 100% speedruns this might be interesting:
100% = all quest in all difficulties + cow kings in all difficulties
-> 84 quests ~ around 1.19% each

so completing den + talking to akara would make 1.19% / 100

Possible to break down into:
Normal x% / 100%
Nightmare x% / 100%
Hell x% / 100%

Total x% / 100%

it does not include waypoints (SDA rules)

Not really a pressious issue - could be sth that puts 100% runs on the boards though.

**Comment by Zutatensuppe** [comment]
note: prepared in dev branch, still need to implement view in main window

**Comment by Zutatensuppe** [comment]
added in v0.3.1 (since pre release 1)
