### ISSUE TITLE
Add possibility to show stats etc vertically

### ISSUE THREAD

**Issue by Teo1904** [Zutatensuppe/DiabloInterface#18]
Same idea as the vertical runes
example how it could look:
[example.zip](https://github.com/Zutatensuppe/DiabloInterface/files/368954/example.zip)

**Comment by Zutatensuppe** [comment]
[vertical.zip](https://github.com/Zutatensuppe/DiabloInterface/files/374881/vertical.zip)
try this attached version. it is not yet ready for release, but should be usable.  :hamster: 

- [x] vertical display
- [ ] add padding (maybe configurable?)
- [ ] add coloring option for items
- [ ] possibly make order of items configurable

**Comment by Zutatensuppe** [comment]
implemented as of v0.3.2 Prerelease 1
