### ISSUE TITLE
Problem with Build

### ISSUE THREAD

**Issue by markpbj** [Zutatensuppe/DiabloInterface#21]
I installed the build, ran as Admin. It will not pull data from my diablo client no matter what I do. Please help. Tried re-installing the interface as well as DII and Expansion

**Comment by markpbj** [comment]
It won't even save my runes from settings into the interface.

**Comment by Zutatensuppe** [comment]
Hi, 
some questions to narrow down the problem:

Which build did u download? Please link to the download or attach a screenshot. (If you didnt alraedy, try using the zip from the latest release: https://github.com/Zutatensuppe/DiabloInterface/releases/latest) 

Do you have Diablo updated to 1.14 ? Also check in interface settings that the same diablo version is selected.
What Operating System are u using?

Runes not getting saved is very strange, the only thing that comes to my mind is a non checked checkbox. To see the runes in the interface, make sure you have added the runes + have checked the Runes checkbox:
![runes](https://cloud.githubusercontent.com/assets/11634723/17041879/9cc7ec5a-4fa9-11e6-9a42-d2d623d3d446.png)

**Comment by markpbj** [comment]
Thanks for getting back so promptly, I have the latest release (double checked) v0.3.1
Diablo is updated to 1.14D and the corresponding version is checked in the settings 
I am running windows 7 currently
![gitmo1](https://cloud.githubusercontent.com/assets/20586512/17041995/180b271a-4f78-11e6-88e3-05f3db46c64f.png)

**Comment by Zutatensuppe** [comment]
That looks kind of wrong. Could it be that you have a retina display? 
Can you try to resize the window? It should show a Panel with lots of checkboxes in the bottom right area, see my screenshot for reference. 

If that does not help, can you see if you have the same problems with this older release: https://github.com/Zutatensuppe/DiabloInterface/releases/tag/v0.3.0 ?

**Comment by markpbj** [comment]
Ok, I tried resizing and that did get me the checkbox selection, so I apologize for not having tried that sooner. Runes fixed. Still not communicating with the d2 client though. I tried the older version as well, same thing. 
I am running on a Lenovo Y50 touch. 
If it is some issue on my end I absolutely cannot pin down what would be preventing the two programs from communicating.

**Comment by markpbj** [comment]
I had a friend just try it and of course he has absolutely no issues. It's very mysterious.

**Comment by Zutatensuppe** [comment]
I suppose you tried everything the same way as your friend?
DiabloInterface tries to find a Process called game.exe, maybe that is called differently at your pc, though this is very unlikely.
Just to be sure, can you see game.exe in the process list of the task manager after u start D2?
Can you upload the last log file (in diablo interface folder there is a sub folder "Logs"), there might be some valuable information.

If nothing else helps, I could try remote help with Teamviewer or something (not now, but later, in the evening? If you like to try that, msg me on twitch, twitch.com/nc_para_ ).

**Comment by markpbj** [comment]
![zut](https://cloud.githubusercontent.com/assets/20586512/17067500/f006f9c2-5019-11e6-9fa7-4762de134798.png)
I figured you would want to give remote view a shot. If you can't think of anything else I would be more than happy to let you have a go. It seems like the game.exe file is in my processes list

**Comment by Zutatensuppe** [comment]
yea, just ask me anytime, when im online and got time, ill try to help u :+1:

**Comment by qhris** [comment]
So we had another weird fixed over at discord, in the end it was because they had an older version of the .NET Framework installed. This is a bit late but mind checking if you have at least **4.5.2** installed? If you already do we'll have to keep digging into this.

Just follow the steps [here](https://msdn.microsoft.com/en-us/library/hh925568(v=vs.110).aspx#net_b) (regedit) to check the DWORD value (not the Version field, it's a bit misleading) and reference to the table below in the link.

If you do not have do not have 4.5.2 or a newer version (4.6) you can get it from the official [microsoft website](https://www.microsoft.com/en-us/download/details.aspx?id=42642).

**Comment by qhris** [comment]
Closing this up because @markpbj didn't respond.
For now I'm going to assume the framework mismatch was the case,
