### ISSUE TITLE
Add support for D2 version 1.14b

### ISSUE THREAD

**Issue by filaname** [Zutatensuppe/DiabloInterface#25]
Could you add a 1.14b version in the latest updates?

**Comment by Zutatensuppe** [comment]
should be possible :)

**Comment by d2blackwolf** [comment]
Yes! The most up-to-date version of its program, but compatible with version 1.14b of Diablo 2.

**Comment by qhris** [comment]
We'd need to find the new memory table for that version since the way data was read was changed a while back, which made a lot of the new features possible. Adding this would be great but someone would have to do the work.

**Comment by filaname** [comment]
How could I help?

**Comment by Zutatensuppe** [comment]
@filaname 
take a look at the pre release: https://github.com/Zutatensuppe/DiabloInterface/releases/tag/v0.3.4.PR.1
