### ISSUE TITLE
Compatibility for 1.13?

### ISSUE THREAD

**Issue by Deltawastaken** [Zutatensuppe/DiabloInterface#28]
Wondering if it's possible to make this useful tool usable with the 1.13 version of this game, I don't have much experience so I'm not sure if it's a hard task or not. I'm also a bit confused on how to make my chat bot interface with the "simple pipe" of the program, apologies if this is something I've overlooked. 

Either way I appreciate the hard work, the tool works wonderfully for the current patches!

**Comment by Deltawastaken** [comment]
Also the item checking function might be easier to use if the items we're output to a text file, either one by one for each slot or in a list style with line breaks. Most chat bots are easy enough to setup with a keyword command to simply output the contents of a txt

**Comment by Zutatensuppe** [comment]
I think the first version we had added in the past was some 1.13, so it should be relatively easy to add backward support. I'll take a look at it later.

concerning bot interaction, you could take a look at the chat bot from @qhris here https://github.com/qhris/DiabloSpeech. He also created this little lib (which is used by the DiabloSpeech bot): https://github.com/Zutatensuppe/DiabloInterfaceAPI

**Comment by Zutatensuppe** [comment]
Small update: first version was for 1.14a, so it will take a longer than expected to update this for 1.13. 😞

**Comment by Deltawastaken** [comment]
Well that's alright, it's not really needed I suppose so don't feel the
need to work on it. I appreciate the response.

**Comment by Deltawastaken** [comment]
I don't know is its rude to offer payment for support, but I've rethought my stance on the matter and I would love D2 Interface/the stream overlay on twitch to work with 1.13 since I stream so often, update me about the status of this feature, or if I can contribute to make it a priority?

**Comment by Zutatensuppe** [comment]
It is rather a matter of time ;) I hope i can look into it in the remainder of this week. I will post here if any progress is made.

**Comment by squeek502** [comment]
Worth noting that the memory layout is quite different between 1.13 and 1.14. In 1.13 (and earlier), things are split into different .dll's and each one contains certain portions of memory. In 1.14, all of those .dll's were combined into the .exe.

**Comment by Zutatensuppe** [comment]
@Deltawastaken Please have a look at the attached file. It supports 1.13c partly. 
The autosplitting functionality is highly likely broken in for 1.13c. When i fix it i will make a proper (pre) release. 📦 

[di_1.13c.zip](https://github.com/Zutatensuppe/DiabloInterface/files/1564633/di_1.13c.zip)

**Comment by Deltawastaken** [comment]
2017-12-16 16:27:25,173 [4] INFO  D2Reader.D2DataReader - Diablo II Process
was found but failed to read memory.

I get this error in the log about every second or so after launching the
game.

**Comment by Zutatensuppe** [comment]
@Deltawastaken Thanks for the report, i ll upload a new version later or tomorrow that hopefully fixes the issue. You probably use 1.13c, right? Not 1.13d?

**Comment by Deltawastaken** [comment]
The main menu of the path of Diablo version simply says 1.13, no letters,
unsure of actual version beyond that.

**Comment by Zutatensuppe** [comment]
Can you give me the value of "File version" of your `Game.exe`? (Right click, properties, Details)
If it is 1.13c it should say `1.0.13.60` and for 1.13d it should be `1.0.13.64`. It does not show the difference ingame unfortunately.

1.13c:
![grafik](https://user-images.githubusercontent.com/11634723/34078290-74242e46-e317-11e7-9a2a-4a608f6d03bc.png)
1.13d:
![grafik](https://user-images.githubusercontent.com/11634723/34078316-1f33fb4a-e318-11e7-973f-cdcd02c58ac2.png)

**Comment by Deltawastaken** [comment]
1.0.13.64 is the file version

**Comment by Zutatensuppe** [comment]
Oh, ok :D

**Comment by Zutatensuppe** [comment]
please try the new attached version. it should support everthing now (1.13C, 1.13D, all the 1.14 versions, item reading, splits, etc) but again, i didnt really have time to test it thoroughly 🕵️ 

[DI_113D.zip](https://github.com/Zutatensuppe/DiabloInterface/files/1565679/DI_113D.zip)

**Comment by Deltawastaken** [comment]
2017-12-17 09:38:30,577 [4] ERROR D2Reader.D2DataReader - Diablo II Process
was found, but the version 1, 0, 13, 64 is not supported.

**Comment by Zutatensuppe** [comment]
hm, are u sure u used the file i uploaded in the previous comment? because it works for me :( 

`2017-12-17 18:22:50,117 [4] INFO  D2Reader.D2DataReader - Found the Diablo II process (version 1, 0, 13, 64).`

**Comment by Deltawastaken** [comment]
Oh boy I hope I'm not being stupid, this cannot work with multiplayer
lobbies, single player only?

If it's single player only.. I am sorry for making you do all that work,
I'm sure plugy mod players will be happy though.

:/

**Comment by Zutatensuppe** [comment]
It was never tried on multiplayer :( It was more intended for singleplayer speedrun. But still, your error message is strange. And it would be interesting to see if this works in multiplayer runs as well. :D

**Comment by Zutatensuppe** [comment]
Branch for 1.13 support has been merged, I opened another issue for the multiplayer support. :)
