### ISSUE TITLE
Issue with Autosplit

### ISSUE THREAD

**Issue by Teo1904** [Zutatensuppe/DiabloInterface#3]
Hi,
I can't seem to make the autosplit work. No matter what hotkey I try it just simply wont split. (the test hotkey in the settings does nothing either)
Yes, I have used the same hotkey on all: Diablo, Livesplit and the Interface.
Yes, I have tried to start all programs as admin. (Which I always did for the interface)
Yes, I have checked the "Enable Autosplit" checkbox.
Yes, I have named the Splits the same way on both Livesplit and the Interface settings.

Greets Teo1904

**Comment by Teo1904** [comment]
Seems like now for whatever random reason it works. (did you change anything apart from the resistance on the resistance hotfix) - in that version the autosplit works.

**Comment by Zutatensuppe** [comment]
Hm, no, only the resistances hotfix. But cool that the autosplit works now. :+1: 

Small note: We know that some keys are not functional yet in that version, like numpad keys for example, but I think it is not so important for now :dash:

**Comment by Teo1904** [comment]
OK have to correct that statement - it starts the splits but it wont split at like Andariel. guess there is still sth wrong.

**Comment by Zutatensuppe** [comment]
could u attach your settings.conf file, please? if it starts the splits, but not split at andariel, there might be something wrong with the config

**Comment by Teo1904** [comment]
There you go:
[settings.zip](https://github.com/Zutatensuppe/DiabloInterface/files/299326/settings.zip)

**Comment by qhris** [comment]
This should be fixed on the pre-release (0.3.0.PR.1). When that version is approved for a real release we'll close this issue.
