### ISSUE TITLE
Show /players value

### ISSUE THREAD

**Issue by Zutatensuppe** [Zutatensuppe/DiabloInterface#38]
There should be an option to show the current `/players` value from the game.

Recently there have been a few requests to show it on stream as `/players X` and `/players 8` categories have been added to the leaderboard.

**Comment by squeek502** [comment]
The technical details (from Discord a while back):

> just did some quick testing for /players X:

> the value is stored in a static memory address relative to d2game.dll (in < 1.14). not sure the real width, but 2 bytes worked alright for me with the following offsets:

> 1.14d: base + 0x00483D70
> 1.13c: d2game.dll + 0x00111C1C

> note: the value does not get initialized (it's zero) until /playersX is actually typed for the first time

> so if the value is zero, its safe to assume the actual value is 1

Complete set of version offsets (from [d2info](https://github.com/squeek502/d2info/blob/master/d2info/offsets.lua)):

> 1.14d: 0x00483D70
> 1.14c: 0x0047ACF8
> 1.14b: 0x0047BDB0
> 1.13d: 0x00111C44
> 1.13c: 0x00111C1C

Also, mentioning @andrew207 who requested this [here](https://github.com/palmettos/D2ID/issues/4)

**Comment by Zutatensuppe** [comment]
Thank you squeek, I created a release taking those infos =)

**Comment by Zutatensuppe** [comment]
Added in v0.4.3
