### ISSUE TITLE
Make the process name configurable.

### ISSUE THREAD

**Issue by Ted-Wang** [Zutatensuppe/DiabloInterface#45]
Now I see the process name is fixed defined in file D2Reader/D2DataReader.cs. 
Can you please make it configurable? I want use it in case run D2 with a different process name.

**Comment by Zutatensuppe** [comment]
@Ted-Wang sure! :)

**Comment by Zutatensuppe** [comment]
@Ted-Wang https://github.com/Zutatensuppe/DiabloInterface/releases/tag/v0.4.8

Added configurable process name. but you have to edit the settings file for that. There is no edit via GUI yet, so you will have to edit the settings file itself. After saving once, you will see something like this, you can edit it as you wish:
```

  "ProcessDescriptions": [
    {
      "ProcessName": "game22",
      "ModuleName": "Game41.exe",
      "SubModules": [
        "D2Common.dll",
        "D2Launch.dll",
        "D2Lang.dll",
        "D2Net.dll",
        "D2Game.dll",
        "D2Client.dll"
      ]
    },
    {
      "ProcessName": "d2se",
      "ModuleName": "D2SE.exe",
      "SubModules": [
        "D2Common.dll",
        "D2Launch.dll",
        "D2Lang.dll",
        "D2Net.dll",
        "D2Game.dll",
        "D2Client.dll"
      ]
    }
  ]
```

**Comment by Ted-Wang** [comment]
@Zutatensuppe Thank you. Actually I want to use this tool in a high screen resolution mode. I patched D2 with D2loader-high.exe. Unfortunately, it seems doesn't work when I setting the process name with "D2loader-high.exe" or "D2loader-high". Anyway, thank you all the same!

**Comment by Zutatensuppe** [comment]
oh, ok, if you can provide more information about the D2loader-high.exe i can look why it isnt working

**Comment by Ted-Wang** [comment]
Actually, I don't know mutch about the patch. I guess it's a wrap program that help to load 3rd party plugins and then call game.exe.
FYI, I upload the patch to Baidu cloud storage, you can get it from this link:
https://pan.baidu.com/s/1Kh8Exaa7XHbgyAbbgGMlJA
the enter code: 7bev

To use this patch, just extract the 3 file to D2 root folder and double click the D2Loader-high.exe, then in the game settings, you can set the screen resolution higher than 800*600, up to 1920*1080.
If your OS is win 7 or higher, you can create a shortcut and set compatible mode to winXP sp3.

I running D2X 1.13c, not sure if it works for other version.

**Comment by Zutatensuppe** [comment]
ok, thank you :) i ll try it out when i have a moment :+1:

**Comment by Ted-Wang** [comment]
Thank you for you god job!

**Comment by Zutatensuppe** [comment]
probably not very interesting anymore as this issue was open for >1 year, but added D2Loader-high support by default. 
it will be part of next release

(note: process name still configurable by editing the config files, so not very convenient. config still mixes application settings + character settings :( )

**Comment by Ted-Wang** [comment]
Thank you so much for your amazing work!
I can see my character's status together with high screen resolution right now!
