### ISSUE TITLE
Rune settings page - "edit" panel is hidden

### ISSUE THREAD

**Issue by ubeogesh** [Zutatensuppe/DiabloInterface#48]
The issue is on 0.4.9 version.

The "Edit" is not visible, and I can't seem to move it to visible area via resizing.

![image](https://user-images.githubusercontent.com/16091685/71659190-c0e72580-2d57-11ea-845e-c33bdab4a88d.png)

**Comment by ubeogesh** [comment]
I have noticed that if I just open the RuneSettingsPage.cs in designer and re-save it; then rebuild the project - the issue is fixed.

**Comment by Zutatensuppe** [comment]
Good find! I indeed use scaled output. Will fix it later, thank you =)

**Comment by Zutatensuppe** [comment]
merged and released :) :+1:
