### ISSUE TITLE
Faster Run/Walk and Increased Attack Speed do not include modifiers from skills

### ISSUE THREAD

**Issue by Zutatensuppe** [Zutatensuppe/DiabloInterface#9]
Faster Run/Walk and Increased Attack Speed currently show only the sum of those attributes on items equipped by player.
They do currently not include modifiers from skills.

There should be an option to turn on "real" values, including skills (and possibly even heavy armor run/walk reduction etc.?)

Skills FRW:
- Vigor (Paladin)
- Increased Speed (Barb)
- Frenzy (Barb)
- Burst of Speed (Assassin)
- Feral Rage (Druid)
_(list may be incomplete)_

Skills IAS:
_(list incomplete)_

**Comment by Teo1904** [comment]
Ias skills:
Werewolf (Druid)
Frenzy (Barb)
Burst of Speed (Assa)
Fanatism (Pala)

**Comment by Zutatensuppe** [comment]
done in develop branch :+1: 
will be included in future version (soon)
