### ISSUE TITLE
Interface Freezes Upon New Hire (edited)

### ISSUE THREAD

**Issue by logicallynx** [Zutatensuppe/DiabloInterface#99]
This is likely a plugy issue as I'm using 1.13c but often, perhaps always, my diablo interface will stop reading/updating stats to both the interface, armory, and diablo.run. The only way to resolve the issue is to close the diablo client and reload this. Closing and re-opening diablo interface will not resolve the issue with any of the 6.X interfaces, however 5.2 will work and read stats. 

This interaction happens after completing A1 (first time through) and continuing to A2, it does not happen in other Acts AFAIK. I have not tested this to see if it's only related to killing quest Andariel but suspect quest bugging Andy may play a roll. Happy to give examples from my stream if that would help resolve the issue. 

Edit: The issue isn't with the transition from A1 to A2, I'm sorry. I just figured out today this happens when hiring a new mercenary (at least in Act 2, perhaps others). The interface locks up after hiring of the new merc. If the merc dies the interface starts working again; If you revive the merc it will lock up again. If I S&E it starts working normally (but this isn't always possible with my runs but I can try to work around it). I'm not sure if this is isolated to A2 mercs but it does occur on normal, and nightmare at least.

**Comment by Zutatensuppe** [comment]
:+1: thanks for providing aditional info , i may find time this week to fix it

**Comment by logicallynx** [comment]
Great, I'm glad I could help. I appreciate all you've done with diablo interface. It's been a wonderful addition to my stream! I don't speed run but it's been very helpful in creating challenge run content for twitch, jsp, and yt. Thanks

**Comment by Zutatensuppe** [comment]
@logicallynx i tried to reproduce it today with the combination of 1.13c/1.13d & diablo interface 6.4

maybe the way i tried to reproduce it was too constructed, what i did (i check amount of gold before and after hiring for easy verification):
- create paladin character
- hero edit it so i can go in act 2
- hire any merc in a2
- hire another merc
- go out of town, go back
- hire another merc
- bug merc
- hire another merc

everything looked fine here :man_shrugging: 

some info that might help:
- diablo interface log files if you have them
- what version of the game u used (1.13c is clear, but what constallation with d2se etc.)
- if possible, minimal steps to reproduce (maybe yt/twitch video like you mentioned is enough to reproduce this)

thanks! <3

**Comment by logicallynx** [comment]
I will clip this from twitch so you can see exactly. I showed it to stream the other day. I can work around it in most instances. But perhaps I didn't explain what happens well enough for you to replicate it.

**Comment by Zutatensuppe** [comment]
It seems to happen even sometimes on a1 merc. at least i could reproduce it by playing the game and not exiting it, and at some point hiring a1 merc. seems i forgot one piece of code when analyzing the asm code :(

bug will be fixed in next release ! :)

**Comment by Zutatensuppe** [comment]
@logicallynx it should be fixed with release https://github.com/Zutatensuppe/DiabloInterface/releases/tag/v0.6.5  
please let me know if you experience the issue with this version too
